# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'converter.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Converter(object):
    def setupUi(self, Converter):
        Converter.setObjectName("Converter")
        Converter.setWindowModality(QtCore.Qt.NonModal)
        Converter.setEnabled(True)
        Converter.resize(229, 273)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Converter.sizePolicy().hasHeightForWidth())
        Converter.setSizePolicy(sizePolicy)
        Converter.setMinimumSize(QtCore.QSize(229, 273))
        Converter.setMaximumSize(QtCore.QSize(229, 273))
        self.centralwidget = QtWidgets.QWidget(Converter)
        self.centralwidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(229, 253))
        self.centralwidget.setMaximumSize(QtCore.QSize(229, 253))
        self.centralwidget.setObjectName("centralwidget")
        self.InBaseBox = QtWidgets.QSpinBox(self.centralwidget)
        self.InBaseBox.setGeometry(QtCore.QRect(40, 140, 42, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InBaseBox.sizePolicy().hasHeightForWidth())
        self.InBaseBox.setSizePolicy(sizePolicy)
        self.InBaseBox.setMinimum(2)
        self.InBaseBox.setMaximum(16)
        self.InBaseBox.setObjectName("InBaseBox")
        self.dial = QtWidgets.QDial(self.centralwidget)
        self.dial.setGeometry(QtCore.QRect(40, 60, 50, 64))
        self.dial.setMinimumSize(QtCore.QSize(50, 64))
        self.dial.setMinimum(2)
        self.dial.setMaximum(16)
        self.dial.setObjectName("dial")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 10, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(10, 190, 121, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.OutBaseBox = QtWidgets.QSpinBox(self.centralwidget)
        self.OutBaseBox.setGeometry(QtCore.QRect(140, 140, 42, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.OutBaseBox.sizePolicy().hasHeightForWidth())
        self.OutBaseBox.setSizePolicy(sizePolicy)
        self.OutBaseBox.setMinimum(2)
        self.OutBaseBox.setMaximum(16)
        self.OutBaseBox.setObjectName("OutBaseBox")
        self.dial_2 = QtWidgets.QDial(self.centralwidget)
        self.dial_2.setGeometry(QtCore.QRect(140, 60, 50, 64))
        self.dial_2.setMinimumSize(QtCore.QSize(50, 64))
        self.dial_2.setMinimum(2)
        self.dial_2.setMaximum(16)
        self.dial_2.setObjectName("dial_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 120, 41, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(140, 120, 47, 13))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(40, 170, 71, 16))
        self.label_4.setObjectName("label_4")
        self.ConvertButton = QtWidgets.QToolButton(self.centralwidget)
        self.ConvertButton.setGeometry(QtCore.QRect(140, 180, 71, 31))
        self.ConvertButton.setObjectName("ConvertButton")
        self.ResultBox = QtWidgets.QLabel(self.centralwidget)
        self.ResultBox.setGeometry(QtCore.QRect(10, 230, 201, 21))
        self.ResultBox.setText("")
        self.ResultBox.setObjectName("ResultBox")
        self.ResultBox = QtWidgets.QLabel(self.centralwidget)
        self.ResultBox.setGeometry(QtCore.QRect(10, 220, 201, 21))
        self.ResultBox.setStyleSheet("background-color:white")
        self.ResultBox.setText("")
        self.ResultBox.setObjectName("ResultBox")
        Converter.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Converter)
        self.statusbar.setObjectName("statusbar")
        Converter.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(Converter)
        self.actionExit.setObjectName("actionExit")

        self.retranslateUi(Converter)
        self.dial.sliderMoved['int'].connect(self.InBaseBox.setValue)
        self.dial_2.sliderMoved['int'].connect(self.OutBaseBox.setValue)
        self.OutBaseBox.valueChanged['int'].connect(self.dial_2.setValue)
        self.InBaseBox.valueChanged['int'].connect(self.dial.setValue)
        QtCore.QMetaObject.connectSlotsByName(Converter)

    def retranslateUi(self, Converter):
        _translate = QtCore.QCoreApplication.translate
        Converter.setWindowTitle(_translate("Converter", "MainWindow"))
        self.label.setText(_translate("Converter", "Base Converter"))
        self.label_2.setText(_translate("Converter", "In Base"))
        self.label_3.setText(_translate("Converter", "Out Base"))
        self.label_4.setText(_translate("Converter", "Number(0:F):"))
        self.ConvertButton.setText(_translate("Converter", "Convert!"))
        self.actionExit.setText(_translate("Converter", "Exit"))

